Lock and Health endpoint
cloudwatt/kube2consul pull request #3
Opened 2017-06-27 14:57 UTC by aevox

2017-06-28 15:25 UTC, fcantournet requested changes

2017-06-28 15:25 UTC, fcantournet commented on main.go
> +		health.RegisterPeriodicThresholdFunc("kubernetes", time.Second*5, 3, kubernetesCheck)
I think we want to check k8s and consul connection health whether or not we want to acquire a consul lock, don't we ?

2017-06-29 08:42 UTC, aevox commented on main.go
> +		health.RegisterPeriodicThresholdFunc("kubernetes", time.Second*5, 3, kubernetesCheck)
Yes indeed, just a slight mix-up.

2017-06-29 10:21 UTC, fcantournet approved these changes

2017-06-29 10:22 UTC, merged